
# Base Stage
FROM node:24-alpine AS base-stage

WORKDIR /code

# Copy package.json and package-lock.json FIRST
COPY package.json package-lock.json ./

# Use npm ci for consistent installs
RUN npm ci

# Copy the rest of the source code AFTER installing dependencies
COPY . .

# Development Stage
FROM base-stage AS dev-stage


# ARG VITE_BACKEND_URL
# ENV VITE_BACKEND_URL=$VITE_BACKEND_URL

EXPOSE 5173

# Start the React app in development mode
CMD ["npm", "run", "dev"] 











# # Base Stage
# FROM node:18-alpine AS base-stage


# WORKDIR /code

# # COPY frontend/package.json ./package.json
# COPY ./package.json ./package.json
# COPY ./package-lock.json ./package-lock.json

# RUN npm install --force --loglevel verbose

# COPY ./ ./

# # Development Stage
# FROM base-stage AS dev-stage

# # COPY /code/env/.env.dev .env

# ARG VITE_BACKEND_URL
# ENV VITE_BACKEND_URL=$VITE_BACKEND_URL

# EXPOSE 5173

# # Start the React app in development mode
# CMD ["npm", "start"]

