FROM node:24-alpine AS build-stage

WORKDIR /code

COPY package.json .

RUN npm install

COPY ../ /code
ENV NODE_OPTIONS="--max_old_space_size=4096"


RUN npm config set loglevel verbose

RUN npm run build

# Serve stage
FROM nginx:alpine AS serve-stage

COPY nginx-prod.conf /etc/nginx/conf.d/default.conf


COPY --from=build-stage /code/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
