services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile.dev
    ports:
      - "5000:8000"
    volumes:
      - ./server:/code
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
      - UVICORN_LOG_LEVEL=debug
      - DEBUG=1
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --reload
    restart: unless-stopped
    env_file:
      - ../.env
    # depends_on:
    #   - redis

  job_processing:
    build:
      context: ./server
      dockerfile: ./Dockerfile.job_processing
    ports:
      - "6000:81"
    volumes:
      - ./server:/code
    restart: unless-stopped
    env_file:
      - ../.env

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./frontend:/code
      - node_modules:/code/node_modules
    network_mode: "host"
    image: cephadex_frontend:1.0
    restart: unless-stopped

  postgres:
    image: postgres:16
    environment:
      PG_DB: db
      PG_USER: user
      PG_PASSWORD: 1234
    restart: unless-stopped
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    command:
      [
        "redis-server",
        "--requirepass",
        "1234",
        "--loadmodule /opt/redis-stack/lib/redisearch.so",
        "--loadmodule /opt/redis-stack/lib/rejson.so",
      ]
# docker-compose -f compose.dev.yml up -d
