# Build stage
FROM node:18-alpine AS build-stage

WORKDIR /code

COPY package.json .

RUN npm install

COPY ../ /code

RUN npm run build

# Serve stage
FROM nginx:alpine AS serve-stage

COPY nginx-prod.conf /etc/nginx/conf.d/default.conf


COPY --from=build-stage /code/dist /usr/share/nginx/html

EXPOSE 80

