
FROM node:18-alpine AS build-stage

WORKDIR /code

COPY package.json .

RUN npm install

COPY ../ /code

RUN npm run build

# Serve stage
FROM nginx:alpine AS serve-stage

COPY nginx-dev.conf /etc/nginx/conf.d/default.conf


COPY --from=build-stage /code/dist /usr/share/nginx/html

EXPOSE 80


# FROM node:18-alpine

# # Create a new user "app" and switch to it
# RUN adduser -D app
# USER app

# WORKDIR /app

# # Ensure the "app" user owns the /app directory
# COPY --chown=app:app package.json package-lock.json ./

# # As "app" user, install dependencies
# RUN npm install

# # Copy the rest of your application code with appropriate ownership
# COPY --chown=app:app . .

# EXPOSE 5173

# CMD ["npm", "run", "dev","--","--host","0.0.0.0"]
# # FROM node:18-alpine

# WORKDIR /app

# COPY package.json package-lock.json ./

# RUN npm install

# COPY . .

# CMD ["npm", "start"]

##
# possibly need to add --chown= to the copy command


