/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export enum Language {
    ENGLISH = 'English',
    FRENCH = 'French',
    SPANISH = 'Spanish',
    GERMAN = 'German',
    PORTUGUESE = 'Portuguese',
    CHINESE = 'Chinese',
    RUSSIAN = 'Russian',
    UKRAINIAN = 'Ukrainian',
    SWAHILI = 'Swahili',
    JAPANESE = 'Japanese',
    DOTHRAKI = 'Dothraki',
    KLINGON = 'Klingon',
    DUTCH = 'Dutch',
    ITALIAN = 'Italian',
    GREEK = 'Greek',
    ARABIC = 'Arabic',
    HINDI = 'Hindi',
    POLISH = 'Polish',
    HEBREW = 'Hebrew',
    FINNISH = 'Finnish',
    NORWEGIAN = 'Norwegian',
    SWEDISH = 'Swedish',
    TURKISH = 'Turkish',
    CZECH = 'Czech',
    ROMANIAN = 'Romanian',
    HUNGARIAN = 'Hungarian',
    BULGARIAN = 'Bulgarian',
    CROATIAN = 'Croatian',
    SERBIAN = 'Serbian',
    ESTONIAN = 'Estonian',
    LATVIAN = 'Latvian',
    LITHUANIAN = 'Lithuanian',
    FARSI = 'Farsi',
    KOREAN = 'Korean',
    INDONESIAN = 'Indonesian',
    VIETNAMESE = 'Vietnamese',
    URDU = 'Urdu',
    PERSIAN = 'Persian',
    THAI = 'Thai',
    MALAY = 'Malay',
    TAGALOG = 'Tagalog',
}
