# # 

# Build stage for installing Python package dependencies
FROM python:3.13 AS builder

WORKDIR /code


COPY ./reqs/requirements.txt /code/

RUN pip install --upgrade -r requirements.txt
## removeing --no-cache-dir 
# Final stage for the runtime environment
FROM python:3.13-slim

# Install runtime dependencies
## Uncomment these dependencies for prod and full testing
RUN apt-get update && apt-get install -y --no-install-recommends \
    # ffmpeg \
    # poppler-utils \
    # tesseract-ocr \
    # tesseract-ocr-eng \ 
    openssl \
    && rm -rf /var/lib/apt/lists/*

# Copy installed Python packages from builder stage

COPY --from=builder /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages

COPY --from=builder /usr/local/bin /usr/local/bin  

RUN pip install uvicorn==0.27.1

COPY ./ /code/

WORKDIR /code

EXPOSE 8000

# Install uvicorn here to ensure the executable is available
# RUN pip install uvicorn
CMD ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "main:app", "--bind", "0.0.0.0:8000"]
