// const languages = [
//   { value: "", label: "Choose a language" },
//   { value: "English", label: "English" },
//   { value: "Arabic", label: "Arabic" },
//   { value: "Bulgarian", label: "Bulgarian" },
//   { value: "Chinese", label: "Chinese" },
//   { value: "Croatian", label: "Croatian" },
//   { value: "Czech", label: "Czech" },
//   { value: "Dutch", label: "Dutch" },
//   { value: "Dothraki", label: "Dothraki" },
//   { value: "Elvish", label: "Elvish" },
//   { value: "Estonian", label: "Estonian" },
//   { value: "Farsi", label: "Farsi" },
//   { value: "French", label: "French" },
//   { value: "German", label: "German" },
//   { value: "Greek", label: "Greek" },
//   { value: "Hebrew", label: "Hebrew" },
//   { value: "Hindi", label: "Hindi" },
//   { value: "Hungarian", label: "Hungarian" },
//   { value: "Indonesian", label: "Indonesian" },
//   { value: "Italian", label: "Italian" },
//   { value: "Japanese", label: "Japanese" },
//   { value: "Korean", label: "Korean" },
//   { value: "Klingon", label: "Klingon" },
//   { value: "Latvian", label: "Latvian" },
//   { value: "Lithuanian", label: "Lithuanian" },
//   { value: "Malay", label: "Malay" },
//   { value: "Norwegian", label: "Norwegian" },
//   { value: "Polish", label: "Polish" },
//   { value: "Portuguese", label: "Portuguese" },
//   { value: "Romanian", label: "Romanian" },
//   { value: "Russian", label: "Russian" },
//   { value: "Spanish", label: "Spanish" },
//   { value: "Serbian", label: "Serbian" },
//   { value: "Swahili", label: "Swahili" },
//   { value: "Swedish", label: "Swedish" },
//   { value: "Tagalog", label: "Tagalog" },
//   { value: "Thai", label: "Thai" },
//   { value: "Turkish", label: "Turkish" },
//   { value: "Urdu", label: "Urdu" },
//   { value: "Vietnamese", label: "Vietnamese" },
// ];
const languages = [
  { value: 0, label: "Choose a language" },
  { value: 1, label: "English" },
  { value: 2, label: "Arabic" },
  { value: 3, label: "Bulgarian" },
  { value: 4, label: "Chinese" },
  { value: 5, label: "Croatian" },
  { value: 6, label: "Czech" },
  { value: 7, label: "Dutch" },
  { value: 8, label: "Dothraki" },
  { value: 9, label: "Elvish" },
  { value: 10, label: "Estonian" },
  { value: 11, label: "Farsi" },
  { value: 12, label: "French" },
  { value: 13, label: "German" },
  { value: 14, label: "Greek" },
  { value: 15, label: "Hebrew" },
  { value: 16, label: "Hindi" },
  { value: 17, label: "Hungarian" },
  { value: 18, label: "Indonesian" },
  { value: 19, label: "Italian" },
  { value: 20, label: "Japanese" },
  { value: 21, label: "Korean" },
  { value: 22, label: "Klingon" },
  { value: 23, label: "Latvian" },
  { value: 24, label: "Lithuanian" },
  { value: 25, label: "Malay" },
  { value: 26, label: "Norwegian" },
  { value: 27, label: "Polish" },
  { value: 28, label: "Portuguese" },
  { value: 29, label: "Romanian" },
  { value: 30, label: "Russian" },
  { value: 31, label: "Spanish" },
  { value: 32, label: "Serbian" },
  { value: 33, label: "Swahili" },
  { value: 34, label: "Swedish" },
  { value: 35, label: "Tagalog" },
  { value: 36, label: "Thai" },
  { value: 37, label: "Turkish" },
  { value: 38, label: "Urdu" },
  { value: 39, label: "Vietnamese" },
  { value: 40, label: "Ukrainian" },
];

export { languages };
