

FROM python:3.12-alpine as builder

WORKDIR /code

RUN apk --no-cache add \
    mariadb-connector-c-dev \
    build-base \
    mariadb-dev

COPY ../../../server/reqs/requirements_cron.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ../../../server/ /code

FROM python:3.12-alpine

WORKDIR /code

COPY --from=builder /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin

COPY ../../../server/ /code

EXPOSE 82

CMD ["python", "-m", "scripts.subrollover"]