const languages = [
  { id: "0", name: "Choose a language" },
  { id: "English", name: "English" },
  { id: "Arabic", name: "Arabic" },
  { id: "Bulgarian", name: "Bulgarian" },
  { id: "Chinese", name: "Chinese" },
  { id: "Croatian", name: "Croatian" },
  { id: "Czech", name: "Czech" },
  { id: "Dutch", name: "Dutch" },
  { id: "Dothraki", name: "Dothraki" },
  { id: "Elvish", name: "Elvish" },
  { id: "Estonian", name: "Estonian" },
  { id: "Farsi", name: "Farsi" },
  { id: "French", name: "French" },
  { id: "German", name: "German" },
  { id: "Greek", name: "Greek" },
  { id: "Hebrew", name: "Hebrew" },
  { id: "Hindi", name: "Hindi" },
  { id: "Hungarian", name: "Hungarian" },
  { id: "Indonesian", name: "Indonesian" },
  { id: "Italian", name: "Italian" },
  { id: "Japanese", name: "Japanese" },
  { id: "Korean", name: "Korean" },
  { id: "Klingon", name: "Klingon" },
  { id: "Latvian", name: "Latvian" },
  { id: "Lithuanian", name: "Lithuanian" },
  { id: "Malay", name: "Malay" },
  { id: "Norwegian", name: "Norwegian" },
  { id: "Polish", name: "Polish" },
  { id: "Portuguese", name: "Portuguese" },
  { id: "Romanian", name: "Romanian" },
  { id: "Russian", name: "Russian" },
  { id: "Spanish", name: "Spanish" },
  { id: "Serbian", name: "Serbian" },
  { id: "Swahili", name: "Swahili" },
  { id: "Swedish", name: "Swedish" },
  { id: "Tagalog", name: "Tagalog" },
  { id: "Thai", name: "Thai" },
  { id: "Turkish", name: "Turkish" },
  { id: "Urdu", name: "Urdu" },
  { id: "Vietnamese", name: "Vietnamese" },
];

export { languages };
